name: duaa_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_animated_button: ^2.0.3
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Jaldi
      fonts:
        - asset: fonts/Jaldi-Regular.ttf
        - asset: fonts/Jaldi-Bold.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/appIcon.png"
